name: "generate-kubeconfig.service"
enabled: true
contents: |
  [Unit]
  Description=Generate Kubeconfig using Kubelet
  Wants=rpc-statd.service crio.service
  After=crio.service afterburn-sethostname.service

  [Service]
  ExecStartPre=/bin/mkdir --parents /etc/kubernetes/manifests
  ExecStartPre=/bin/rm -f /var/lib/kubelet/cpu_manager_state
  EnvironmentFile=/etc/os-release
  EnvironmentFile=-/etc/kubernetes/kubelet-workaround
  EnvironmentFile=-/etc/kubernetes/kubelet-env

  ExecStart=/usr/local/bin/generate-kubeconfig.sh
  
  Type=oneshot

  [Install]
  WantedBy=multi-user.target
