filesystem: "root"
mode: 0755
path: "/usr/local/bin/generate-kubeconfig.sh"
contents:
  inline: |
    #!/bin/bash

    /usr/bin/timeout 900 /bin/bash -c -- \
    'while true; do \
      /usr/bin/hyperkube \
      kubelet \
        --config=/etc/kubernetes/kubelet.conf \
        --bootstrap-kubeconfig=/etc/kubernetes/kubeconfig \
        --rotate-certificates \
        --kubeconfig=/var/lib/kubelet/kubeconfig \
        --container-runtime=remote \
        --container-runtime-endpoint=/var/run/crio/crio.sock \
        --node-labels=node-role.kubernetes.io/master,node.openshift.io/os_id=${ID} \
        --minimum-container-ttl-duration=6m0s \
        --volume-plugin-dir=/etc/kubernetes/kubelet-plugins/volume/exec \
        --register-with-taints=node-role.kubernetes.io/master=:NoSchedule \
        --v=3; done'
    
    echo "Finishing kubeconfig generation"
